### ISSUE TITLE
Ingest UI uploaded files are registered with absolute path instead of relative

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#223]
Files uploaded via the Ingest UI are registered with the full, absolute path to the file.  Only the relative path beneath the directory named for the file uuid should be registered, for example:
  `/hubmap-data/hm_uploads/1785aae4f0fb8f13a56d79957d1cbedf/ffec7d19f92c7bca56f74d45df507e82/HubMap007_Spleen_9.JPG`
should be registered as only:
  `HubMap007_Spleen_9.JPG`

- fix all current registrations in the current database
- update the code that creates these registrations (in ingest-api, I think..) to only register relative paths for new registrations

**Comment by kburke** [comment]
This command should fix all the files.PATH absolute references in the current hm_uuid Production database:
```
UPDATE `hm_uuid`.`files`
SET `PATH` = substring_index(PATH,'/',-1)
WHERE `PATH` LIKE '/hive/hubmap/hm_uploads/%'
```
Verified this is the only prefix and subdirectories beneath the file UUID directory do not exist.

Will wait to execute until ingest-api changes ready to check in.

**Comment by kburke** [comment]
Within the ingest-api project, the `UploadFileHelper.commit_file()` method needs to an absolute path to the uploaded file location to be returned to it once the file UUID is assigned, so that file system directories can be cleaned up.  Specifically, the file must move from `hm_uploads_tmp` to the appropriate location under `hm_uploads`.

This, the actually place to assure only the relative part of the file path is stored on files.PATH is actually in the uuid-api project, in `UUIDWorker.newUUIDs()`.  N.B. this method must still populate its `file_path` variable with an absolute path, for return to ingest-api.

**Comment by kburke** [comment]
Create https://github.com/hubmapconsortium/uuid-api/pull/106 and https://github.com/hubmapconsortium/ingest-api/pull/227 to resolve issue and enhance logging.

**Comment by kburke** [comment]
Executed SQL [in comment above ](https://github.com/hubmapconsortium/ingest-api/issues/223#issuecomment-1191878585)on Production, affecting 362 rows.

**Comment by kburke** [comment]
Executed on Test (362 row, recent copy of Prod), on Stage (278 rows), and Dev (359 rows).

**Comment by yuanzhou** [comment]
Thanks @kburke, do you think I'll need to reindex these changes too? Not sure if the file path info gets to Elasticsearch.
