### ISSUE TITLE
Update to Flask v3.x

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#557]

**Comment by yuanzhou** [comment]
https://flask.palletsprojects.com/en/3.0.x/changes/

**Comment by ChuckKollar** [comment]
Testing criteria is to execute six endpoints:
1) GET/PUT/POST on traditional (e.g. app. decorators),
2) GET/PUT/POST on a Blueprint decorators

NOTE: I have removed the requirement on the atlas-consortia-commons package
because it was using a pinned version of Flask, and moved the functions from it that
are being used in this micro-service to the utils directory.

**Comment by ChuckKollar** [comment]
PR: https://github.com/hubmapconsortium/ingest-api/pull/570

**Comment by ChuckKollar** [comment]
Used python3 -m pyanalyze to catch some coding errors. Same PR.
