### ISSUE TITLE
Validate that donor data required to generate Dataset title exists

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-api#60]
Verify that the age, race and sex records exist in the donor metadata of the donor attached to a dataset which is being validated.  This information is needed by the [generate_dataset_title](https://github.com/hubmapconsortium/ingest-api/blob/d4c74cfd656a8c7c93b5052a0c8e1decba7e745e/src/dataset_helper.py#L85) method.

Add this to the validation suite managed by Joel@psc.

**Comment by ChuckKollar** [comment]
Talk with Joel at the PSC.

**Comment by ChuckKollar** [comment]
There is a new endpoint in ingest-api '/datasets/<uuid>/verifytitleinfo' that will be called by the ingest-pipeline.
This endpoint has yet to be wired up to the pipeline. There is a start on that in GitHub, but more work needs to be done since this is the first time that this code has called a microservice.

**Comment by shirey** [comment]
Closing.  No longer valid with new derived title field.
